### ISSUE TITLE
类A继承B，使用Chain构造sql语句时，会报类B非Entity（没加Table注解），实际类B的确非数据库表映射类，只是一些公共字段

### ISSUE THREAD

**Issue by 51734** [mybatis-mp/mybatis-mp#17]

**Comment by Ai-010** [comment]
类A上 是否是 实体类注解 ？还有你使用的版本是几 ？我在测试中 也有类似的，不过没问题

**Comment by Ai-010** [comment]
如果B类中的字段确实不是数据库列，可以使用@Igore 注解 忽略，如果是的话，应该是有其他原因

**Comment by Ai-010** [comment]
![QQ_1733109111136](https://github.com/user-attachments/assets/8829cd4e-e9e8-4ed6-a8b2-fd755750c80d)
![QQ_1733109124920](https://github.com/user-attachments/assets/5a5d5ede-d100-4e9a-825d-19a521351173)
测试了 均没有问题

**Comment by Ai-010** [comment]
欢迎进去，这样能得到快速的回复
