### ISSUE TITLE
Solved pain points than other frameworks issue

### ISSUE THREAD

**Issue by Noel443** [mybatis-mp/mybatis-mp#18]
I would like to know what new features this framework has compared to mybatis-plus? I have looked at the documentation in detail and found no advantages over mybatis-plus. If so, please let me know and I will be able to make a comparison. The following technology selection is one of the options

**Comment by Ai-010** [comment]
Compared to mybatis plus, there are many differences:
1: We can join multiple tables
2: We support XML pagination
3: We can support multiple databases simultaneously
4: Has stronger mapping ability for non entity classes
5: There are more convenient capabilities, such as @Fetch, dynamic default values, @PutValue, @Putenum Value
....
There are many more, you can go to my official website: see https://mybatis-mp.cn ！
